### ISSUE TITLE
Request for the code with Gazebo simulator

### ISSUE THREAD

**Issue by yangshuo11** [matiov/learn-BTs-with-GP#1]
Many thanks for providing such a wonderful work! I am currently utilizing the GP algorithms for controlling the Tiago robot in the Gazebo simulator. I noticed that you could provide the Gazebo version code to the readers. Could you please share the code with me for my own research purposes. Thanks in advance!

**Comment by yangshuo11** [comment]
My email address is 1024809808@qq.com. Many thanks!

**Comment by AaronVG99** [comment]
Hi! Before hand I would like to thank you for the content of this repository.
 
I am very interested and currently researching about GP and learning BT currently working with a TIAGo robot. I was wondering if you could share your code for the gazebo implementation of the resulting behavior trees since I have seen that you offer it. 

Thank you in advance for your time.

**Comment by ZhangQuan-hub** [comment]
I am a student studying BT with GP.I notice you can provide the gazebo world and make code run on that.Could you please send me the gazebo code to me ?My email is a19190363@neau.edu.cn.Thank you.

**Comment by matiov** [comment]
Hello,

Thank you for your interest in the repository and my work. Please send an email to matteo.iovino@se.abb.com 
I will answer to the email providing a link to download the code for the Gazebo Simulation.
